title: MMAUG Community Articles
description: Technical articles from the Malta Microsoft AI User Group community
theme: jekyll-theme-cayman
markdown: kramdown
url: https://mmaug-org.github.io
baseurl: /community-articles
future: true

collections:
  articles:
    output: true
    sort_by: date
    permalink: /articles/:title/

defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "article"

leaderboard_api_url: "https://script.google.com/macros/s/AKfycbz0-H12vW9BeWbFP_nsYatmg5hUAp2-NjVJYwawFQTwa-DAtvOUOIXh_bzfU38WYVWHdg/exec"
leaderboard_api_token: ""
